apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-marvel
  labels:
    name: hero-manager-marvel
spec:
  selector:
    matchLabels:
      name: hero-manager-marvel
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-marvel
    spec:
      containers:
        - name: hero-manager-marvel
          image: gcr.io/hero-manager2210610/hero_manager_marvel_image:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources: {}
          env:
            - name: MARVEL_URL
              value: https://gateway.marvel.com
            - name: MARVEL_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: marvel-api-public-key
                  key: public
            - name: MARVEL_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: marvel-api-private-key
                  key: private
            - name: PORT
              value: "8082"


          
