apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-backend
  labels:
    name: hero-manager-backend
spec:
  selector:
    matchLabels:
      name: hero-manager-backend
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-backend
    spec:
      containers:
        - name: hero-manager-backend
          image: gcr.io/hero-manager2210610/hero_manager_backend_image:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources: {}
          env:
            - name: PORT
              value: "8081"
          envFrom:
            - configMapRef:
                name: hero-manager-database-configmap
