apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-statistics
  labels:
    name: hero-manager-statistics
spec:
  selector:
    matchLabels:
      name: hero-manager-statistics
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-statistics
    spec:
      containers:
        - name: hero-manager-statistics
          image: gcr.io/hero-manager2210610/hero_manager_statistics_image:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          resources: {}
          env:
            - name: PORT
              value: "8083"
          envFrom:
            - configMapRef:
                name: hero-manager-database-configmap
